%Creates without training the tutorial network for digits from matlab
function [deepnet] = untrained_enc_enc_soft_net(x, t)
    autoenc1 = trainAutoencoder(x,100, ...
        'MaxEpochs',1, ...
        'L2WeightRegularization',0.004, ...
        'SparsityRegularization',4, ...
        'SparsityProportion',0.15, ...
        'ScaleData', false, ...
        'ShowProgressWindow', false);
    feat1 = encode(autoenc1,x);

    autoenc2 = trainAutoencoder(feat1,50, ...
        'MaxEpochs',1, ...
        'L2WeightRegularization',0.002, ...
        'SparsityRegularization',4, ...
        'SparsityProportion',0.1, ...
        'ScaleData', false, ...
        'ShowProgressWindow', false);
    feat2 = encode(autoenc2,feat1);

    softnet = trainSoftmaxLayer(feat2,t,'MaxEpochs',1, 'ShowProgressWindow', false);
    deepnet = stack(autoenc1,autoenc2,softnet);
end

